spring.application.name=rentacar_spring
# 1. Veritaban? Adresi: localhost, port 5432, veritaban? ad? 'rentacar'
spring.datasource.url=jdbc:postgresql://localhost:5432/rentacar
spring.datasource.username=postgres
spring.datasource.password=12345

# 2. KR?T?K SATIR: Tablolar? otomatik olu?tur/güncelle
spring.jpa.hibernate.ddl-auto=update

# 3. Konsolda SQL'leri göster (Tablo olu?tururken 'create table' yaz?s?n? görmek için)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialecwt.PostgreSQLDialect